### ISSUE TITLE
Status cerebro nupic-studio? 

### ISSUE THREAD

**Issue by breznak** [numenta/nupic.cerebro2#69]
@chetan51 Is cerebro obsoleted?

@david-ragazzi are you reusing the code? or providing same functionality? 

or is there a chance of merging the two projects?

**Comment by david-ragazzi** [comment]
> @david-ragazzi are you reusing the code? or providing same functionality?

@breznak Actually `nupic.studio` is quite different from `cerebro`. It is a full (desktop) toolkit for users create, change and debug HTM networks (in this case, the nupic code itself) and is fully implemented in python. As far I know, `cerebro` is a (web-based) HTM debugger implemented in javascript and others. 

> or is there a chance of merging the two projects? 

An idea would be `nupic.studio` re-implement some debug code from cerebro2 and we retire cerebro2. I'm quite favor of this, but this not depends of me. Numenta guys have access to pull improvements to nupic.studio, so if they want use it as main tool, they are very welcome.
